### ISSUE TITLE
Mobile > Applications and Profile swapped

### ISSUE THREAD

**Issue by BillCampbell** [zdorow/DeviceGroupTool#1]
When I ran the program with Mobile and Applications selected, it created the text file 11.27.2017MobileApps.txt but that file contained a listing of profiles, not apps.  When I run profiles I get the list of apps in 11.27.2017MobileProfiles.txt

JAMF Pro version 10.0.0-t1508873342
336 mobile device apps in the catalog
about 40 smart mobile device groups
8 static device groups
17 smart user groups
33 static user groups

**Comment by zdorow** [comment]
Ah thanks I will get that fixed!

**Comment by zdorow** [comment]
Uploading the correct version now.
