### ISSUE TITLE
Suggestion for output format

### ISSUE THREAD

**Issue by BillCampbell** [zdorow/DeviceGroupTool#2]
In response to your[ post on JAMFnation asking for suggestions on output](https://www.jamf.com/jamf-nation/feature-requests/1874/show-where-a-smart-group-is-used#responseChild21099), I offer the following:

For each item/group pairing (e.g. apps) I suggest you output a separate line in your text file with the app and group as comma separated values.  That will result in multiple lines per app but this could then be easily pulled into a spreadsheet and sorted by group or by app/item.

**Comment by zdorow** [comment]
Ok I was thinking of outputting to CSV and that should be fairly easy to do. Thanks for the quick feedback!

**Comment by zdorow** [comment]
I was able to get the .csv output to work and plan on adding formatting later for the columns. 
Let me know what you think! More to come!
